/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as FilmesRouteImport } from './routes/filmes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as FilmeIdRouteImport } from './routes/filme.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmesRoute = FilmesRouteImport.update({
  id: '/filmes',
  path: '/filmes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmeIdRoute = FilmeIdRouteImport.update({
  id: '/filme/$id',
  path: '/filme/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favoritos': typeof FavoritosRoute
  '/filmes': typeof FilmesRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/filme/$id': typeof FilmeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favoritos': typeof FavoritosRoute
  '/filmes': typeof FilmesRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/filme/$id': typeof FilmeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favoritos': typeof FavoritosRoute
  '/filmes': typeof FilmesRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/filme/$id': typeof FilmeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/favoritos' | '/filmes' | '/login' | '/registro' | '/filme/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/favoritos' | '/filmes' | '/login' | '/registro' | '/filme/$id'
  id:
    | '__root__'
    | '/'
    | '/favoritos'
    | '/filmes'
    | '/login'
    | '/registro'
    | '/filme/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritosRoute: typeof FavoritosRoute
  FilmesRoute: typeof FilmesRoute
  LoginRoute: typeof LoginRoute
  RegistroRoute: typeof RegistroRoute
  FilmeIdRoute: typeof FilmeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filmes': {
      id: '/filmes'
      path: '/filmes'
      fullPath: '/filmes'
      preLoaderRoute: typeof FilmesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filme/$id': {
      id: '/filme/$id'
      path: '/filme/$id'
      fullPath: '/filme/$id'
      preLoaderRoute: typeof FilmeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritosRoute: FavoritosRoute,
  FilmesRoute: FilmesRoute,
  LoginRoute: LoginRoute,
  RegistroRoute: RegistroRoute,
  FilmeIdRoute: FilmeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
